spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**


        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**


  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone : ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
